### PR TITLE
Fix some problems of number functions, add some similar number functions, add several quick access menus.

### PR DESCRIPTION
**Pull request by GitPopcorn**
#### Fix some problems of number functions, add some similar number functions, add several quick access menus.

- Fix problems below:
	- The number function did not work well in multi-selection mode.
		Only the last selection will be replaced because of the key duplication of "selectionMap"
	- The sequence function only make sequence for each selection in multi-selection mode, a global sequence can not be create.
		And it just seems like to be not working when we got only one number in each selection.
- Add functions below:
	- duplicateNumAndIncrement: Duplicate the number part and increment new number copies
	- duplicateNumAndDecrement: Duplicate the number part and decrement new number copies
	- incrementWithZero: Increment all numbers with 0 paddings at left
	- decrementWithZero: Decrement all numbers with 0 paddings at left
	- duplicateAndIncrementWithZero: Duplicate and increment all numbers with 0 paddings at left
	- duplicateAndDecrementWithZero: Duplicate and decrement all numbers with 0 paddings at left
	- duplicateNumAndIncrementWithZero: Duplicate the number part and increment new number copies with 0 paddings at left
	- duplicateNumAndDecrementWithZero: Duplicate the number part and decrement new number copies with 0 paddings at left
	- sequenceWithZero: Sequence all numbers with 0 paddings at left (starting with first number)
- Add quick access menus below:
	- showAllFunctionTypes: Show all function types
	- showAllFunctions: Show all functions
	- showAllStringFunctions: Show all string functions
	- showAllNumberFunctions: Show all number functions
	- showAllNumberIncrementFunctions: Show all number increment functions
	- showAllNumberDecrementFunctions: Show all number decrement functions
	- showAllNumberSequenceFunctions: Show all number sequence functions

### CODE REVIEW

**Comment by marclipovsky** [comment]
Generally good with this, I'll check it out an run thru the new commands. 

Could you run this thru eslint and format? I see some joined lines and var's in there.

**Comment by GitPopcorn** [comment]
> Generally good with this, I'll check it out an run thru the new commands.
> 
> Could you run this thru eslint and format? I see some joined lines and var's in there.

I have run the eslint and find only two errors about async/await keyword, no other format warning found. I have fixed the 'var' declaration and single-line method manually.
In addtion, we need to add eslint-babel to the dev dependencies as eslint parser later to avoid this lint error.

Beyond that, the biggest problem is the installing and compiling error. It is according to the problems of vscode engine. The url `https://vscode-update.azurewebsites.net/api/releases/stable` using in script `./node_modules/vscode/bin/install` has been replaced as `https://update.code.visualstudio.com/api/releases/stable` and can not be accessed anymore, so the compile process just crash.

And there do be many other issues like this, e.g., report 'No tsconfig.json founded' when run install (Because the `install` script will actually call tsc, but what we have is a `extension.js`).

When developed I create a local mock servcer, manully modify the script, and finally deprecated the two lifecycles `vscode:prepublish` and `compile` to solve this, it do be a headache to me.

In the latest code template of `yo code`, these lifecycles and dependency `vscode` has been removed. Compiling command turns to use `tsc` straightly and test process turns to depend on `@vscode/test-electron`. So my suggestion is to completely change dev dependencies and vscode engines to the new version, if you permit, I will push the changes later.

**Comment by GitPopcorn** [comment]
> Generally good with this, I'll check it out an run thru the new commands.
> 
> Could you run this thru eslint and format? I see some joined lines and var's in there.

Sorry for the test failure, I have passed it earlier and forgot to run it again after the quick fix of eslint. It changed the statement "== null" to "=== null", made the test failed...
A good lesson for me to always run test finnally, sorry again. I have fixed it and pushed a new commit.

**Comment by marclipovsky** [comment]
@GitPopcorn I've updated mocha. Could you fix conflicts? Then we will check the CI results.

**Comment by GitPopcorn** [comment]
> @GitPopcorn I've updated mocha outside of this PR. Sorry looks like you did as well and you fixed the mocha color option flag. Could you fix conflicts (take your mocha color option change)? Then we will check the CI results.

Alright, I have sync the main repository, merge the code changings and finish unit test/behaviour test and try to apply a new pull request based on the lasted version. But should I update the version of plugin to 0.5.8 by myself? or to 0.5.8-SNAPSHOT? or should I just leave the version alone?

**Pull request closed without merging**
